# -*- coding: utf-8 -*-
INSTALLED_APPS = ["django.contrib.admin"]

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
ALLOW_CERTIFICATE_PUSHING = True 
SECURE_FRAME_DENY = False
X_FRAME_OPTIONS = "SAMEORIGIN"
