# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneToUsernameMapping',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
