# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

import os
import sqlite3

class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_instant_schools_plugin', '0001_initial'),
    ]

    # this is a dummy migration that should no longer do anything; it's now handled more correctly in the migratev1database command