# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_instant_schools_plugin', '0002_import_old_hashed_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
