# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-31 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_instant_schools_plugin', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneHashToUsernameMapping',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneToUsernameMapping',
        ),
    ]
