# Generated by Django 3.2.25 on 2025-01-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_instant_schools_plugin', '0005_aboutfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfaq',
            name='kind',
            field=models.TextField(choices=[('FAQ', 'FAQ'), ('About', 'About'), ('Terms', 'Terms')]),
        ),
    ]
